[workspace]
members = ["toml-comment", "toml-comment-derive"]
resolver = "2"

[workspace.package]
version = "0.2.0"
edition = "2024"
authors = ["z1xus"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/z1xus/toml-comment"
readme = "README.md"
